### PR TITLE
Added Vietnamese

### PR DESCRIPTION
**Pull request by crystaltype**

### CODE REVIEW

**Comment by crystaltype** [comment]
I signed it!

**Comment by alexeiva** [comment]
thank you very much @crystaltype! @m4rc1e could you review this?

**Comment by m4rc1e** [comment]
I wish people would regenerate the fonts, once they've amended the .glyphs files. 

This is why we need fontmake hooked up to a release system. Keep the binaries out of github :-)

I'll take a look now.

**Comment by m4rc1e** [comment]
Its pretty good.

The Vietnamese has correct components and all glyphs are present.

scada-vietnamese


The version number needs bumping to v4.100 and the fonts need regenerating. Other than that, its good.

**Review by m4rc1e — CHANGES_REQUESTED** [review]
Its pretty good.

The Vietnamese has correct components and all glyphs are present.

scada-vietnamese


The version number needs bumping to v4.100 and the fonts need regenerating. Other than that, its good.

**Comment by alexeiva** [comment]
@crystaltype please increase version number to 4.100, and generate the fonts (ttf and otf) to the fonts folder.

**Comment by crystaltype** [comment]
Done! Thank you Alexei and Marc!

**Pull request merged**
